LABS-EU3/quality_hub_frontend

package-lock.json, quality_hub/src/App.js, quality_hub/src/components/Marketplace.jsx, quality_hub/src/components/devices.jsx
Creates a Marketplace page in React
Creates a devices.jsx page to centralise responsiveness options using styled components
For user to be able to see all coaches available.
go to /marketplace and test responsiveness using google analytics
As a user I want to be able to see all stories
=> Jayne marketplace

package-lock.json
My landing page in new dir structure
=> pulled from dev branch and refactored landing page

src/components/Forms/InterviewerForm.js, src/components/Forms/LoginForm.js, src/components/Forms/SignUpForm.js, src/components/Forms/StudentForm.js, src/components/Landing.js, src/components/UserType/UserTypePage.js, src/components/UserType/styles.js
Add navigation to forms
Add navigation to logo on all forms to route to the landing page
click on the logo on any form and make sure your navigated to the correct page
As a user i can navigate back to the landing page wherever i am##  Screenshots (If appropriate)
=> Onboarding form styling

src/components/Forms/InterviewerForm.js, src/components/Forms/LoginForm.js, src/state/actions/authenticationActions.js
Fixes the coach form not working due to 500 from the server
Edit skill_level and description fields to pass correct values from form
Sign up as coach
=> fix bug in interviewerform: skill_level being passed description string

src/App.js, src/components/Cards/FeedbackCard.js, src/components/Inputs/FeedbackInput.js, src/components/Modals/FeedbackModal.js, src/views/Feedback/GiveFeedback.js
Styles give feedback page
Add styling to give feedback page
Go to dashboard and click on interview, check you see a styled give feedback page
as a user i want to be able to give feedback (styles)
=> Give feedback styles

src/components/Chat/Chat.js, src/components/Chat/ChatScreen.js, src/components/Chat/SendMessage.js, src/components/Chat/UserList.js
Adds styling to chat
Stylings added to various components in chats
Go to chats and check the stylings
Styling Chat
=> Styling Chat component

src/components/Cards/EmptyAppointmentCard.js, src/components/Cards/EmptyFeedbackCard.js, src/components/Dashboard.js, src/components/FAQ/Main.js, src/views/Feedback/Feedback.js, src/views/UserDashboard/UserDashboard.js
- Integrates the top data bar in dash with the new title
- Stops the top navbar from overlapping content
- Stop pagination and copyright from overlapping
- Stop FAQ from overlapping
Fix dashboard styling bugs
Visit dashboard and FAQ
Fix broken styles in dashboard, make nav bar transparent
=> Dom dash styling

src/components/Cards/FeedbackCard.js, src/components/DataVisualization/StudentChart.js, src/views/Feedback/Feedback.js
Adds in feedback chart again, this component can be improved but want it pushed up so people can see it
Add in a container component, tweak graph properties, add in to Feedback view
visit app/feedback
As a user I want to be able to visualize my interview feedback
=> Dom charts again

src/components/Dashboard.js, src/views/Feedback/Feedback.js
Makes the sidebar responsive
Automatically collapses the sidebar when on mobile view
Go the web app and check on mobile width size
Sidebar responsive
=> reduce the side bar of the material ui dashboard component

src/components/Onboarding/AccountRecovery.js, src/components/Onboarding/ResetPasswordForm.js, src/state/actions/bookingActions.js
account recovery/password reset
account recovery/password reset
click forgot password on the login form and follow the prompt
as a user I want to be able to reset my password
=> cleared warnings from console

package-lock.json, package.json, public/index.html, src/components/Code/Editor.js, src/components/Code/Interface.js, src/components/Code/Terminal.js, src/components/Interview/Code.js, src/index.js, src/utils/executionHelpers.js, src/views/Code/Code.js
Updates code execution to allow running sample tests
refactor code execution to use async await in for of loop
update Interface and Editor components
Visit Code tab
As a user I want to be able to execute code
=> Dom code execution

src/components/Code/Terminal.js, src/components/Interview/Code.js, src/components/Interview/Participant.js, src/components/Interview/Room.js, src/components/Interview/Terminal.js, src/views/Interview/Interview.js
Bring video chat into a panel below terminal
Make video panel responsive to sidebar size changes
Restyle and move buttons
Integrate video with editor styling
Click interview button
As a user I want to be able to execute code
=> Dom code styling

src/components/Booking/BookingStyles.js, src/components/Booking/DatePicker.js, src/components/Inputs/FeedbackInput.js, src/views/Feedback/GiveFeedback.js
Makes the review form and booking page responsive
Adds media queries for mobile and tablet width for responsiveness when needed
Go to the application and check the components
Responsive review form
Responsive Booking page
=> Responsive Review Form and  Booking Page

src/components/Chat/ChatScreen.js, src/components/Chat/MessageList.js, src/components/Chat/SendMessage.js, src/components/Chat/UserList.js
Adds responsiveness to chat page
Adds responsiveness to various screen sizes
Go the application and view on smaller screens
responsive design, Chat page
=> Responsive chat page

src/components/Cards/EmptyAppointmentCard.js, src/components/Dashboard.js, src/components/Onboarding/Login/LoginStyles.js, src/views/Feedback/Feedback.js, src/views/UserDashboard/UserDashboard.js
fix feedback and dashboard spacing
fix feedback and dashboard spacing
go to dashboard and feedback pages on both user types and check styling is consistent on small and large screens
Feedback graph display none if no feedback
=> Dashboard styles

src/App.js, src/components/Chat/ChatScreen.js, src/components/Chat/MessageList.js, src/components/Chat/UserList.js, src/components/Onboarding/AccountRecovery.js, src/state/actions/authenticationActions.js, src/state/actions/chatActions.js, src/state/reducers/appointments.js, src/state/reducers/chat.js, src/state/reducers/marketplace.js, src/views/Marketplace/Marketplace.js, src/views/UserDashboard/UserDashboard.js
This Pull Request is for fixing  multiple small bugs
- fix chat image bug
- fix chat name bug
- fix chat loader bug
- fix dashboard loader bug
- order appointments per date
- locally: go to the Netlify dev link and test the application
[Trello Card](https://trello.com/c/KV2Jk2op/180-bugfix-on-student-profile-chat-names-display-first-name-twice-instead-of-first-and-last-name)
=> Chat / Loader bugs

src/components/Interview/Code.js
This Pull Request is for fixing the live broadcast bug on select language and select testcase 
- add async await to booth select functions on the code component
- add multiple syncUpdate function calls
- locally: go to the Netlify dev link and test the application
[Trello Card](https://trello.com/c/KV2Jk2op/180-bugfix-on-student-profile-chat-names-display-first-name-twice-instead-of-first-and-last-name)
=> live broadcast fix 

src/components/Cards/AppointmentCard.js, src/components/Chat/MessageList.js, src/components/Reschedule/RescheduleAppointmentStepper.js, src/views/Settings/SettingsTabs.js
styling settings and reschedule appointment page
styling settings and reschedule appointment page
Navigate to profilesettings and update Info/cancel an appointment and follow the prompt
style polishment
=> Oladimeji styling

src/components/Booking/BookingStepper.js, src/components/Booking/DatePicker.js, src/components/Cards/AppointmentCard.js, src/components/Cards/CoachCard.js, src/components/Code/Terminal.js, src/components/DataVisualization/StudentChart.js, src/components/Inputs/SelectInfo.js, src/components/Reschedule/RescheduleAppointmentStepper.js, src/state/reducers/marketplace.js, src/utils/executionHelpers.js, src/utils/mappers.js
Various styling fixes across the app as discussed earlier: restyle cards in dashboard and marketplace, restyle payments page
Ensure styling is polished
Visit home dashboard, marketplace, booking
Format payments page, ensure all options available in marketplace
=> Dom styling fixes

src/components/Cards/CoachCard.js, src/components/Code/Interface.js, src/components/Interview/Code.js, src/utils/executionHelpers.js, src/utils/mappers.js
Tests now show expected output as well as whether they fail or pass. Update C state with cooler problem. Add these changes into terminal as well as editor. Fix experience mapper for Dan in marketplace
=> Dom demo fixes

src/components/Booking/BookingStyles.js, src/components/Booking/DatePicker.js, src/components/Onboarding/UserType.js, src/components/Settings/SettingsGeneral.js, src/components/Settings/SettingsStyles.js
Fix settings console error
Fix settings console error
go to settings > general tab and check console
=> Payment styling

src/components/Code/Interface.js, src/utils/executionHelpers.js
Add more code challenges to the code editor
Add more code challenges to the code editor
Navigate to code 
add more test cases
=> Oladimeji test cases

src/components/Cards/CoachCard.js, src/components/Code/Editor.js, src/components/Code/Interface.js, src/components/Interview/Code.js, src/utils/executionHelpers.js
Adds in new languages, tweaks editor styling to align run button better ad prevent video window being hidden. Prevents running tests in languages other than JS
=> Dom editor fixes

src/components/FAQ/FaqStyles.js, src/components/Inputs/SearchForKeyword.js, src/components/Inputs/SelectExperience.js, src/components/Inputs/SelectPrice.js, src/views/Marketplace/Marketplace.js
Improves search and filter bar in the marketplace
Adds more stylings to select price, search keyword and select experience
Go to the application and check the marketplace
improve search and filter bar in the marketplace
=> Improve search and filter bar

src/App.js, src/components/Cards/ChallengeCard.js, src/utils/challenges.js, src/utils/dashboardList.js, src/views/Challenges/Challenges.js
This Pull Request is for adding the code challenge library prototype
-  add code challenge library component
- locally: go to the Netlify dev link and test the application
[Trello Card](https://trello.com/c/ogj0t0uC/203-bugfix-cancel-appointment-not-working)
=> Library Prototype

src/components/Code/Interface.js, src/utils/challenges.js, src/utils/executionHelpers.js, src/views/Challenges/Challenges.js
This Pull Request is for adding python tests and a go back to challenges button
-  add python tests
- add go back to challenges button
- locally: go to the Netlify dev link and test the application
[Trello Card](https://trello.com/c/ogj0t0uC/203-bugfix-cancel-appointment-not-working)
=> Python tests / go back button
